### ISSUE TITLE
Error while creating RecordingOptions 

### ISSUE THREAD

**Issue by prabhat2k15** [CyCoreSystems/ari#103]
I am trying to record the bridge and i am using 
**func (bh *BridgeHandle) Record(name string, opts *RecordingOptions) (*LiveRecordingHandle, error)**
 to record the bridge.

I have created RecordingOptions struct to pass in the params
```
var recOpt *ari.RecordingOptions
 recOpt.Format = "wav"
 recOpt.Exists = "overwrite"
 _, err = bridgeHandle.Record("testrec", recOpt)
```

i get the following error at runtime.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x691a89]

goroutine 20 [running]:
stasis.ensureBridge(0x96c780, 0xc000188000, 0x970740, 0xc000122000, 0xc0000b2cd0, 0x2, 0xc00006ac60)
        /home/prabhat/go/src/stasis/stasis.go:128 +0x199
stasis.app(0x96c780, 0xc000188000, 0x970740, 0xc000122000, 0xc000148810)
        /home/prabhat/go/src/stasis/stasis.go:96 +0x340
created by stasis.App
        /home/prabhat/go/src/stasis/stasis.go:56 +0x8f0
exit status 2

What am i doing wrong?

**Comment by Ulexus** [comment]
Since you don't supply the line numbers, I cannot be sure, but I am reasonably certain that the problem is in your definition of `recOpt`.  You are defining that a pointer exists, but you are not instantiating an instance of `ari.RecordingOptions`.

Use something like:

```go
var recOpt = &ari.RecordingOptions{
  Format: "wav",
  Exists: "overwrite",
}
```

or

```go
recOpt := new(ari.RecordingOptions)
recOpt.Format = "wav"
recOpt.Exists = "overwrite"
```

**Comment by prabhat2k15** [comment]
great...wroked..
