### ISSUE TITLE
Changing the state of a channel to UP

### ISSUE THREAD

**Issue by ehsanrocket** [CyCoreSystems/ari#104]
hello
I know whether I should call an extension and pass it to the  `stasis` app or 
create the channel and `dial()` it, so the channel should answer the call so that it's channel change to UP
is there any way to change a state of a channel to UP without make a channel to dial an extension or dialing the channel ?

**Comment by Ulexus** [comment]
I'm not sure I understand your question.  The generic means of changing the state of the channel to UP is to call `.Answer()`.

**Comment by ehsanrocket** [comment]
this is my code

    func main() {
	     log.Info("Connecting to ARI")
             cl, err := native.Connect(&native.Options{
		Application:  "xx",
		Username:     "ss",
		Password:     "dd",
		URL:          "http://localhost:8088/ari",
		WebsocketURL: "ws://localhost:8088/ari/events",
	    })

	    if err != nil {
		    log.Error("Failed to build ARI client", "error", err)
		    return
	    }

	    app := cl.ApplicationName()
        a := ari.Key{Kind: ari.ChannelKey, ID: "12345", Node: "caller", App: app}
	    b := ari.ChannelCreateRequest{"SIP/admin", app, "", a.ID, "", "", ""}

	    h, err := cl.Channel().Create(&a, b)
     	    if err != nil {
	     	    fmt.Print("Cannot call", err)
	         }
       }

in the "http://localhost:8088/ari/channels" the channel's state is **Down**

I created a ChannelHandle in a another file and ran **h.Answer()**, but nothing happened
**h.Hangup()** worked correctly but **.Answer()** do nothing

**Comment by ehsanrocket** [comment]
It returns this error : 
**Non-2XX response: 412 Precondition Failed**

**Comment by Ulexus** [comment]
You have not actually made the channel live.  Somewhat confusingly for new people, ARI (from Asterisk) provides the create method to separately create a channel from its induction into the system.  The idea is that you can create the channel, modify its parameters, and then call Dial on it to make it live.

So what Asterisk is complaining about here is that the channel is not live, so you cannot Answer() it.  You need to call Dial() on it, first.

You probably want to use Originate() here, which does both in one step.

**Comment by ehsanrocket** [comment]
as you said  "You need to call Dial() on it, first" , I did it.
I called Dial() method, so the channels'  state goes from Down to Ringing. then I used the Answer() method. it returns : **Non-2XX response: 412 Precondition Failed**

And when I use Originate(), it Create and Dial the channel at the same time 
but when I use the Answer() method, it returns : **Non-2XX response: 409 Conflict**

I just want to Answer the ringing Channel without pressing the Answer button in Zoiper or any SIP Phones

here is my code:

    func main() {
	    log.Info("Connecting to ARI")
	    cl, err := native.Connect(&native.Options{
            Application:  "xx",
		Username:     "ehsan",
		Password:     "esx",
		URL:          "http://192.168.43.227:8088/ari",
		WebsocketURL: "ws://192.168.43.227:8088/ari/events",
	})
	if err != nil {
		log.Error("Failed to build ARI client", "error", err)
		return
	}

	app := cl.ApplicationName()

    a := ari.Key{Kind: ari.ChannelKey, Node: "caller", App: app}
	b := ari.OriginateRequest{Endpoint: "SIP/h5", App: app, CallerID: "test", Timeout: 300}

	h, err := cl.Channel().Originate(&a, b)
	if err != nil {
		fmt.Print("Cannot call : ", err)
	}

	time.Sleep(5 * time.Second)
	fmt.Println("##########################################################")

	err = h.Answer()
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println("yes")
	}
    }
