### ISSUE TITLE
Bridge Recording not saving on Custom path

### ISSUE THREAD

**Issue by prabhat2k15** [CyCoreSystems/ari#105]
I am using bridgehandle.Record(filename, recOption) function to record my calls  and it is working fine for saving the recording to default path i.e. /var/spool/asterisk/recording

But I want to save the recording to another path. I have tried giving path in record function 
bridgehandle.Record("custompath"+filename, recOption)

But its not saving the recording on the given path and also not on default path.

There is no option of giving path on Recording Option also.

How can i save the bridged recording to my path?

**Comment by Ulexus** [comment]
So far as I am aware, this is a limitation of Asterisk.  We are passing the name as sent.  If it isn't working, then it is either a restriction from Asterisk or Asterisk does not have permission to write to whatever custompath you are specifying.  

**Remember** that Asterisk generally runs as a non-root user, and so it needs permission to write to arbitrary directories.
