### ISSUE TITLE
Playback without playback id

### ISSUE THREAD

**Issue by vipul-sharma20** [CyCoreSystems/ari#107]
Hi,

Asterisk has two ways start a media playback on the channel:
* [With playback ID](https://wiki.asterisk.org/wiki/display/AST/Asterisk+16+Channels+REST+API#Asterisk16ChannelsRESTAPI-playWithId)
* [Without playback ID](https://wiki.asterisk.org/wiki/display/AST/Asterisk+16+Channels+REST+API#Asterisk16ChannelsRESTAPI-play)

From the code and the doc I could only find the implementation where the playback ID is mandatory (1st API). Do we have the implementation of the 2nd API (playback without specifying playback ID) in the library?

Thanks.
Vipul

**Comment by Ulexus** [comment]
No, because you would have no way or tracking or controlling it without an ID.  However, I would not have a problem with internally generating the playback ID so that the user needn't do so.  That seems like a reasonable feature.

**Comment by Ulexus** [comment]
It was actually already partially implemented.  When using StagePlay, it would generate a playback ID, but when calling Play directly, it would not.

Now, both bridge- and channel-based play methods will accept an empty playback ID, internally generating one.

**Comment by Ulexus** [comment]
Fix is live in v5.0.0-pre6
