### ISSUE TITLE
Answering a Ringing Channel 

### ISSUE THREAD

**Issue by ehsanrocket** [CyCoreSystems/ari#108]
hello, I have created a channel. and then I called Dial() method, so the channels'  state goes from Down to Ringing. then I used the Answer() method. it returns : **Non-2XX response: 412 Precondition Failed**

And when I use Originate(), it Create and Dial the channel at the same time 
but when I use the Answer() method, it returns : **Non-2XX response: 409 Conflict**

I just want to Answer the ringing Channel without pressing the Answer button in Zoiper or any SIP Phones

here is my code for Originate:

    func main() {
	    log.Info("Connecting to ARI")
	    cl, err := native.Connect(&native.Options{
            Application:  "xx",
		Username:     "ehsan",
		Password:     "esx",
		URL:          "http://192.168.43.227:8088/ari",
		WebsocketURL: "ws://192.168.43.227:8088/ari/events",
	})
	if err != nil {
		log.Error("Failed to build ARI client", "error", err)
		return
	}

	app := cl.ApplicationName()

    a := ari.Key{Kind: ari.ChannelKey, Node: "caller", App: app}
	b := ari.OriginateRequest{Endpoint: "SIP/h5", App: app, CallerID: "test", Timeout: 300}

	h, err := cl.Channel().Originate(&a, b)
	if err != nil {
		fmt.Print("Cannot call : ", err)
	}
I get the Id of the channel and from a another file try to answer it:

    key1 := ari.Key{Kind: ari.ChannelKey, ID: "01dp1wssktx7hhvkxhw5tca8a1-ch", Node: "caller", App: app}
	h := cl.Channel().Get(&key1)
	fmt.Print(h)
	err = h.Answer()
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println("yes")
	}
    }

**Comment by Ulexus** [comment]
No telephony system will allow you to force the called party to answer from the calling party's side.  Imagine that a SPAM caller could force your phone to answer their call!

That said, many endpoints (soft phone, in your case) allow you to configure it to Auto-Answer, either always or due to a set of preconditions.
