### ISSUE TITLE
DTMF passthrough

### ISSUE THREAD

**Issue by DevHossamAli** [CyCoreSystems/ari#112]
Hi All,

**How i could disable DTMF passthrough on a bridge?**

I have a bridge with multiple parties when party A hits a digit all other peers could hear the tone, i want only the channel with active DTMF event to hear it if possible.

currently using Asterisk 17

**Comment by Ulexus** [comment]
You can disable DTMF passthrough on bridges using the [AbsorbDTMF](https://pkg.go.dev/github.com/CyCoreSystems/ari/v5?tab=doc#BridgeAddChannelOptions) option to [bridge.AddChannelWithOptions](https://pkg.go.dev/github.com/CyCoreSystems/ari/v5?tab=doc#Bridge).

```go
br.AddChannelWithOptions(channelToAdd, &ari.BridgeAddChannelOptions{
  AbsorbDTMF: true,
})
```
