### ISSUE TITLE
Recording and file format

### ISSUE THREAD

**Issue by karlmccracken** [CyCoreSystems/ari#113]
Hi everyone,

When I try to apply the recording example, that you provided, I get this weird warning:

![](https://lh3.googleusercontent.com/-bOOF6awTbDc/XsGkS8kxXCI/AAAAAAAAA2k/y7bQhuVALdsfTyJlp62jCaSr6YWhEsxzACK8BGAsYHg/s0/2020-05-17.png)

and the file gets created in the recording path, but with no content.
But, when I provide the format record.Format("WAV"), it works just fine.

Any ideas?

**Comment by Ulexus** [comment]
Asterisk is a bit weird with its wav formats.  The default case (which is `wav`) in the example is a more standard wav format:  signed linear.  The one you used (`WAV` in all caps) indicates GSM format.  Your error indicates that your Asterisk isn't able to convert the µLaw from your calling device to the signled-linear of the wav file.  But apparently you _can_ transcode to GSM.
