### ISSUE TITLE
DeviceStateChanged event missing data

### ISSUE THREAD

**Issue by qoole** [CyCoreSystems/ari#114]
The 'DeviceStateChanged' event seems to be missing some of the data that should be contained.

For example, the following ARI event:
`{"type":"DeviceStateChanged","application":"hello-world","timestamp":"2020-05-23T18:32:40.750+0100","device_state":{"name":"PJSIP/1000","state":"NOT_INUSE"},"asterisk_id":"42:01:0a:9a:00:06"}`

Provides the following event from the ARI library:
`"&{EventData:{Application:hello-world Dialog: Node:42:01:0a:9a:00:06 Timestamp:2020-05-23 18:32:40.75 +0100 BST Type:DeviceStateChanged} Header:map[] DeviceState:{Key:<nil> State:NOT_INUSE}}"`

As you can see the 'name' field is missing, so there is no way of telling WHICH device has changed state.

**Comment by qoole** [comment]
changing the DeviceStateData struct in device.go to the following resolves the issue:
```GO
type DeviceStateData struct {
	// Key is the cluster-unique identifier for this device state
	Key *Key `json:"key"`

	State string `json:"state"`
	Name string `json:"name"`
}
```

**Comment by Ulexus** [comment]
Thanks.  I hadn't noticed that we are not interpreting the key.  Since a device does not necessarily correspond to a channel, we can't actually encode it as a key... but we _should_ still have _something_ to map to a key.  Perhaps we need to add a "device" key.

**Comment by Ulexus** [comment]
Hrmm.  We _have_ a devicestate key already, so it _should_ have been mapped.  I'll check into this.
