### ISSUE TITLE
placing calls

### ISSUE THREAD

**Issue by i0x71** [CyCoreSystems/ari#115]
Is there a way to place a call ?

Thanks

**Comment by Ulexus** [comment]
There are a number of ways, depending on your needs:
  - `client.Channel().Create()` : this will create a channel but not actually _dial_ it, meaning that you can manipulate it and customize it before Asterisk actually creates it
  - `client.Channel().Originate()`: this is the normal means of creating and dialing a new channel
  - you can also use Create and Originate from an existing channel handle, which will make sure that the new channel is:
    - on the same Asterisk node as the reference channel
    - is codec-compatible with the reference channel

**Comment by i0x71** [comment]
Thanks alot for a quick response, is there somewhere i can read about the particulars of using client.Channel().Create()

**Comment by Ulexus** [comment]
Basically, call `client.Channel().Create()`.  You will be given a `ChannelHandle`.  Feel free to manipulate it as you wish before dialing.  Generally, this means setting up event watchers, adding SIP headers, or adding channel variables.  When you are ready call the `Dial()` function on the `ChannelHandle` to cause Asterisk to actually perform the connection.

**Comment by i0x71** [comment]
Perfect, thanks alot!
