### ISSUE TITLE
ari3 - List() Design

### ISSUE THREAD

**Issue by sheenobu** [CyCoreSystems/ari#12]
Many of the interfaces (bridge, application) need List methods. The v2 code all return []Bridge, []Application, etc.

Should the new List interface methods return []BridgeHandle or []BridgeData?

**Comment by Ulexus** [comment]
It should return handles.  The `Data()` methods of Handles should return the data.

**Comment by Ulexus** [comment]
From handles, data can be obtained.  Data does not beget handles.
