### ISSUE TITLE
ari 3.0 - ari.Player, ari.Play design.

### ISSUE THREAD

**Issue by sheenobu** [CyCoreSystems/ari#15]
We have this global ari.Play function in v2. How do we want to handle this in v3?

I think we want to move the global ari.Play function to client?

The items implementing ari.Player would be the Handles (ChannelHandle, BridgeHandle). The handles would be responsible for converting the common ari.Player call to their specific transports. client.Play still handles general lifecycle operations via Bus interactions.

Big changes:
 * ari.Play is now ari.Client.Play.
 * ari.Play does NOT take a x/net/context.
 * ari.Play returns an object which can be operated on (and hooked into x/net/context).

Assumptions:

 * the Bus that allows Playback event subscriptions is transport agnostic, like the other items within ari.Client.

Usage:
```
val, err := client.Play(handle, mediaURI)
defer val.Stop()
```

Methods, entiies:

```
/// implemented by ChannelHandle, BridgeHandle, etc
type Player interface {
    Play(string) (string, error)
}
```

```
// An interface or struct or anything else
type PlaybackOperation ? {
    Stop()
}
```

```
func (cl *Client) Play(p Player, mediaURI string) (PlaybackOperation, error) {
    ... current implementation, which subscribes to the clients event Bus ...
}
```

Other options/notes:

 * We can make ari.Player a namespaced interface, with different lifecycle managements for each transport.
 * Like the first, but part of ari.Playback.
 * ari.PlaybackQueue hasn't even been mentioned yet

**Comment by Ulexus** [comment]
Operations for Playbacks should be under the Playback namespace on Client.

There is a PlaybackHandle in the same way as there is a Channel handle and a Bridge handle.

The Play operations also exist on each playable handle, ChannelHandle and BridgeHandle.  The PlaybackHandle is an operator for a Playback, which exists in Asterisk ARI, however, I would say that we should have some additional helper functions like we do now.

For the macro operation the top-level Play does now (as well as the related Prompt), I think it should be in a submodule/package "audio" and simply wrap the lower level methods, keeping any channel, bridge, Player, client, etc, metadata inside its instantiation.

```go
package audio

// Play plays a set of audio samples through, to completion or abortion
func Play(ctx context.Context, /* etc */) error {
}

// PlayAsync starts the playback of a set of audio samples, returning a Playback
// for further manipulation.
func PlayAsync() *Playback {
}

/* ... */
```

I also think this should include:
  - audio URI helpers
  - Prompt helpers and presets

These might be best broken out into their own packages:  `audiouri` and `prompt`.

**Comment by Ulexus** [comment]
So the base layer, I agree, should not receive a context.Context, but I still think the higher-level helper functions should, where appropriate (such as the one-shot, play-to-the-end `audio.Play()`).

**Comment by sheenobu** [comment]
alright: ari.Bridge,  ari.Channel (and their Handles) return *ari.PlaybackHandle types
