### ISSUE TITLE
Adding a call to a bridge

### ISSUE THREAD

**Issue by chiefMarlin** [CyCoreSystems/ari#157]
Hi,
I have looked through channels Create and Originate functions and it looks like they must have either an app or an extension linked to them, which from my understanding does not simply create a channel but rather establishes a link between the dialed party and either an app or an extension.
In my use case i'm simply trying to place a call to a remote number and add it to a local existing bridge.
What would be the best way to do that ?

Thanks

**Comment by Ulexus** [comment]
They do not require one.  You can pass a `nil` for the reference resource.
