### ISSUE TITLE
Found a problem with ari.Bridge.StageCreate()

### ISSUE THREAD

**Issue by ClarenceYk** [CyCoreSystems/ari#74]
https://github.com/CyCoreSystems/ari/blob/e4c85dc96d3eeb05f68e60f49e886f04ff4c2626/client/native/bridge.go#L42

I think it should be `return b.client.post("/bridges/"+key.ID, nil, &req)`

**Comment by Ulexus** [comment]
Aha, thanks!  Would you like to submit a PR for the fix?

**Comment by ClarenceYk** [comment]
Sorry, I don't know how to make a PR, so you can fix that by yourself :)

BTW thanks for your great work, it helps me a lot.

**Comment by Ulexus** [comment]
Okay, thanks for the catch!
