### ISSUE TITLE
changes in satori/go.uuid gives error when run `go get`

### ISSUE THREAD

**Issue by devishot** [CyCoreSystems/ari#81]
There [satori/go.uuid#66](https://github.com/satori/go.uuid/issues/66) mentioned changes for uuid.NewV1(). Now it also return error. 
It causes an error:

> client/native/bridge.go:28:22: multiple-value uuid.NewV1() in single-value context
> client/native/bridge.go:140:26: multiple-value uuid.NewV1() in single-value context
> client/native/channel.go:92:29: multiple-value uuid.NewV1() in single-value context
> client/native/channel.go:121:29: multiple-value uuid.NewV1() in single-value context
> client/native/channel.go:343:23: multiple-value uuid.NewV1() in single-value context
> client/native/client.go:89:33: multiple-value uuid.NewV1() in single-value context

**Comment by Ulexus** [comment]
We don't have a good solution to this right now.  `satori/go.uuid` has not released a new version tag, but its `master` branch has a breaking change.  We are referencing the latest (`v1.2.0`) tag in our version dependency specifications, so we recommend using `glide` or `dep` to control your version dependencies until such time as we can restore `go get`ability (when `satori/go.uuid` releases a tag which is API compatible with its `master` branch).

**Comment by Ulexus** [comment]
Closed by #86 (no longer using UUID library)
