### ISSUE TITLE
More tutorials

### ISSUE THREAD

**Issue by kylegibbons** [CyCoreSystems/ari#84]
I appreciate all the work you've done to make this library. but I'm having a hell of a time navigating it on my own. Everything seems to be a circular reference, for instance when I want to create a channel for an out outbound call everything I can find seems to require a channel as input. A tutorial on creating channels would be very helpful, among others.

**Comment by Ulexus** [comment]
Creating channels in Asterisk is its own, rather complicated thing.  Generally, you would "Originate" a new channel.

Can you give me a bit more information about what you are trying to accomplish?  I'd be happy to add more examples in the `_examples/` directory to better suit your use case.

**Comment by kylegibbons** [comment]
Thanks for getting back to me.

What I'm trying to do right now is basically create a queue app with a ringall strategy. There's a lot more I plan to do, but that's what I'm stuck on right now. My plan is to have the call come in, continue to ring the line, then ring all the members of the queue where the first to answer will get bridged to the caller.

I looked at Originate too and I'm still confused because the signature looks like this func (*ChannelHandle) Originate, which seems to indicate I need to already have a ChannelHandle, and NewChannelHandle also takes a channel as an argument. Maybe I'm just thinking about it all wrong, but origination is really confusing me.

**Comment by Ulexus** [comment]
In this scenario, you shouldn't have to create a channel manually.  A call will be coming into Asterisk.  In the Asterisk dialplan, you will add an extension which directs the call to `Stasis(<appname>)`, where `<appname>` is the name you register your ARI application as.  At that point, any call which hits that Asterisk extension will be sent to your ARI app, leaving you with a ChannelHandle, which is a manipulation wrapper for a channel, and with which most of your operations will be.

I have added a [README](https://github.com/CyCoreSystems/ari/blob/master/_examples/play/README.md) to the "play" example, which should hopefully make clear what you should expect.  If it is insufficient, please let me know what pieces I'm missing.

**Comment by Ulexus** [comment]
As for the Originate usage, there are two entries for Originate.  Most commonly, you Originate a new channel as _related_ to an existing channel.  The `func (*ChannelHandle) Originate()` method handles that association.  Basically, you have a call come in and then you want to create a new branch which goes somewhere else:  `h.Originate()` will handle that for you.

A bare `ariClient.Channel().Originate()` provides the lower level call, which does not automatically associate the channel which is to be created with an existing one.  This would be used in cases where you have an announcer or dialer making a call without an associated one.

**Comment by Ulexus** [comment]
In your case, you will want to use the associated `Originate()` since you are creating new channel(s) which will be associated with the inbound caller's channel.

**Comment by kylegibbons** [comment]
Thank you for all that information, I am making use of the bridge example.

I was finally able to originate a call. One confusing thing is which parameters to choose for OriginateRequest. I was watching for errors, but even though I was passing invalid parameters I wasn't getting any. 

Now, the call does go through, but I don't get any events for it. Is it because I'm dialing it based on Extension and not providing an app?

This is my mockup code:

```
outCall1, err := incomingCall.Originate(ari.OriginateRequest{
		Endpoint: "PJSIP/1111",
		//Context:   "Dial-Users",
		Extension: "1111",
		//Priority:  1,
		//ChannelID: "QUEUE:" + newUUID.String(),
		CallerID: "Production Queue",
		Timeout:  30,
	})

	if err != nil {
		fmt.Printf("can't originate call: %v", err)
	}

	sub1 := outCall1.Subscribe(ari.Events.All)

	for {
		select {
		case e := <-sub1.Events():
			fmt.Println("here")
			v := e.(*ari.StasisStart)
			log.Info("Got stasis start", "channel", v.Channel.ID)
			//go app(ctx, cl.Channel().Get(v.Key(ari.ChannelKey, v.Channel.ID)))
		case <-qm.ctx.Done():
			return
		}
	}
```

**Comment by kylegibbons** [comment]
OKay, I was able to determine that the reason for not getting the events was that I wasn't sending the call through the app. It's a little confusing because a call that's originally in your app will then come back through Stasis start. I handled this case with AppArgs.

One question I did have is why is AppArgs a string and Args an array of string when it reenters the app?

I think it would be helpful to have more documentation on the OriginateRequest struct so you can understand which options are required/optional and what the effect is of using different sets. Also, error messages for invalid args would be a HUGE help!

Thanks again for writing such a complete library for ARI!

**Comment by Ulexus** [comment]
I didn't want to reproduce all of the Asterisk documentation in this library, but yes, it is confusing.  

Originate may well accept the command (thus producing no error), but the call itself may fail.  This is why there is a StageOriginate, which allows you to stage (basically, just create the origination channel locally), bind your event subscriptions to it (to watch for things like ChannelDestroyed events), and then Exec it when everything is ready.   For fast failures (like invalid options), this is pretty important.

AppArgs vs Args.... good point.  They really should be parallel... but that's how ARI is set up.  We get the Args as a (JSON) array from the StasisStart event, but they are sent as a comma-separated string in the Originate.  I'm not sure I want to break the current API to make that more parallel... but perhaps I could add an `Args` property which could be used instead, to be more parallel.

As for the docs, I presume you have looked at the [godoc](https://godoc.org/github.com/CyCoreSystems/ari#OriginateRequest) for the OriginateRequest, right?  What do you think that needs?

**Comment by Ulexus** [comment]
Actually, those comments are pretty bad... they were obviously written by someone who didn't know what they were.  I'm updating the docs for that now.

**Comment by Ulexus** [comment]
Improved by 98fdbe4391d5e49bafd2f2a0e52c86f61dce4148
