### ISSUE TITLE
Originate

### ISSUE THREAD

**Issue by DevHossamAli** [CyCoreSystems/ari#92]
Please provide a working **Originate** sample.

**Comment by Ulexus** [comment]
Thanks.  I see now that there is no such example.   I will try to cobble something sensible together.

**Comment by DevHossamAli** [comment]
Many thanks

**Comment by devishot** [comment]
I will support @Ulexus that using channels and bridges is more preferable than originate calls.

There is video from Asterisk Conference: https://www.youtube.com/watch?v=7nujWPFcftc
Where said about using flexibility of ARI than builded logic, like Asterisk Queue and Originate.

**Comment by DevHossamAli** [comment]
i understand that depending on the core building blocks like bridges and channels will bring more flexibility in the development process but for busy developers or starters it's always preferable to simplify the API and functionality and by doing so you'll save their time.

**Comment by Ulexus** [comment]
@DevHossamAli Are you still wanting an explicit Originate example, or was my reference (above) sufficient?

**Comment by DevHossamAli** [comment]
yes the reference was sufficient, many thanks
