### ISSUE TITLE
return error?

### ISSUE THREAD

**Issue by stgnet** [CyCoreSystems/ari#93]
https://github.com/CyCoreSystems/ari/blob/f95c2e345c3db214e9580cac735e296cb67cbd60/client/native/request.go#L115

Should this not return err?

**Comment by devishot** [comment]
> [ari/client/native/request.go](https://github.com/CyCoreSystems/ari/blob/f95c2e345c3db214e9580cac735e296cb67cbd60/client/native/request.go#L115)
> 
> Line 115 in [f95c2e3](/CyCoreSystems/ari/commit/f95c2e345c3db214e9580cac735e296cb67cbd60)
> 
>  return 
> Should this not return err?

@stgnet this is normal behaviour for Go - Named Return Values.

This chapter from tutorial prodives simple example:
https://tour.golang.org/basics/7

Also, there is open issue for remove this behaviour which may lead to misunderstanding: https://github.com/golang/go/issues/21291

**Comment by stgnet** [comment]
I understand that it is legal to return nil here, but my concern is that an error that prevents the request from being completed should return an error in this case, just like the other cases of return in this function.

**Comment by Ulexus** [comment]
@stgnet It is returning an error here, if an error is returned by the request.

Stylistically, though, this function is not pleasant, since it mixes using implicit (named) returns with explicit returns.  That, at least, should be fixed.
