### ISSUE TITLE
cannot have two active apps simultaneously

### ISSUE THREAD

**Issue by ehsanrocket** [CyCoreSystems/ari#96]
Hi all
I have two stasis app 
A and B :
`exten => 2018,1,NoOp()`
      `  same =>      n,Answer()`
      `  same =>      n,stasis(A)`
      `  same =>      n,Hangup()`

`exten => 2019,1,NoOp()`
       ` same =>      n,Answer()`
       ` same =>      n,stasis(B)`
       ` same =>      n,Hangup()`

and two ari user :
`[ehsan]`
`type = user`
`read_only = no`
`password = esx`

`[busy]`
`type = user`
`read_only = no`
`password = check`

I connect to the asterisk through WebSocket by user "ehsan" to create app "A"
`cl, err := native.Connect(&native.Options{`
		`Application: "A",`
		`Username:    "ehsan",`
		`Password:    "esx",`
		`URL:          "http://localhost:8088/ari",`
		`WebsocketURL: "ws://localhost:8088/ari/events",`
	`})` 
`....`

but when I want to create app B through WebSocket by user "busy" it will deactivate the app "A" first 
and then creates the app "B"
` Deactivating Stasis app 'A'`
`Activating Stasis app 'B'`

and also logs :
WARNING[9361]: res_http_websocket.c:516 ws_safe_read: Web socket closed abruptly
WARNING[9361]: ari/ari_websockets.c:126 ast_ari_websocket_session_read: WebSocket read error: Success

base on this link I can have two active apps simultaneously : 
https://wiki.asterisk.org/wiki/display/AST/Getting+Started+with+ARI
how can I have two active apps simultaneously in golang ari !?

**Comment by Ulexus** [comment]
Yes, you should absolutely be able to have multiple ARI applications connected at the same time.  I have never actually tried it from the same program, but it _should_ work.  I'll see if I can set up a local test.

**Comment by Ulexus** [comment]
No, I have no problem running two simultaneous apps from the same program.  I'd have to guess there is something wrong with your code.

Test code [here](https://play.golang.org/p/TUVX1lY59N-).

**Comment by ehsanrocket** [comment]
thank you, but when I run code like bridge sample (https://github.com/CyCoreSystems/ari/blob/master/_examples/bridge/main.go)
from two separate: A.go and B.go
asterisk logs these : 

` Creating Stasis app 'A'`
  == WebSocket connection from '127.0.0.1:59018' for protocol '' accepted using version '13'
WARNING[17195]: res_http_websocket.c:516 ws_safe_read: Web socket closed abruptly
WARNING[17195]: ari/ari_websockets.c:126 ast_ari_websocket_session_read: WebSocket read error: Success
` Deactivating Stasis app 'A'`
` Shutting down application 'A'`
` Destroying Stasis app A`
  == WebSocket connection from '127.0.0.1:59018' closed
` Creating Stasis app 'B'`
  == WebSocket connection from '127.0.0.1:59022' for protocol '' accepted using version '13'

A.go : app=A , user=ehsan, password=esx
B.go : app=B , user=busy , password=check

**Comment by ehsanrocket** [comment]
I use liteide for writing go codes
when I run A.go and then B.go 
at the firsts line of  B.go output I see :

Killing current process...
Error: process crashed or was terminated while running.

while all the programs have been stopped

**Comment by Ulexus** [comment]
I do not know what lideide is, but it sounds like whatever you are running the code through is only allowing a single process to run at a given time.  Just compile and run each directly, and I suspect you will be fine.

**Comment by ehsanrocket** [comment]
oh yes, the problem was IDE 
thank you very much 
just can you tell me what is the proper IDE for golang

**Comment by Ulexus** [comment]
I use [neovim](https://neovim.io), so I don't really know anything about IDEs.

**Comment by Ulexus** [comment]
I do know that lots of IDE-type people use Microsoft's thing... [VSCode](https://github.com/Microsoft/vscode), and that there is a decent [Go plugin](https://github.com/Microsoft/vscode-go) for that.

**Comment by ehsanrocket** [comment]
oh yes. thank you very much Ulexus
